name: dotnet-mkdocs-material
description: >
  Build .NET project(s) and MkDocs Material site.
  Supports multi-project targeting with per-project docs output.
author: Erik Goughnour
branding:
  icon: book
  color: blue

inputs:
  dotnet_version:
    description: ".NET SDK version to install."
    required: false
    default: "8.0.x"

  python_version:
    description: "Python version for MkDocs."
    required: false
    default: "3.12"

  configuration:
    description: ".NET build configuration."
    required: false
    default: "Release"

  projects:
    description: |
      Newline-separated list of .NET project paths to build.
      Each project generates docs into docs/api/<project-name>/.
      Leave empty to build the repository root (original single-project behavior).
    required: false
    default: ""

  site_name:
    description: "Site name for generated mkdocs.yml (ignored if mkdocs.yml exists)."
    required: false
    default: "API Documentation"

  strict:
    description: "If true, run mkdocs build with --strict."
    required: false
    default: "false"

  build_site:
    description: "If true, run mkdocs build. Set to false to only generate markdown (useful when RTD handles the build)."
    required: false
    default: "true"

  dotnet_build_args:
    description: "Extra args appended to dotnet build."
    required: false
    default: ""

  mkdocs_build_args:
    description: "Extra args appended to mkdocs build."
    required: false
    default: ""

outputs:
  site_dir:
    description: "Path to the built site directory (empty when build_site is false)."
    value: ${{ inputs.build_site == 'true' && 'site' || '' }}
  docs_dir:
    description: "Path to the docs directory containing generated markdown."
    value: docs

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Build .NET project(s)
      shell: bash
      run: |
        set -euo pipefail
        PROJECTS="${{ inputs.projects }}"

        if [ -z "$PROJECTS" ]; then
          echo "::group::dotnet build (single project)"
          dotnet build -c "${{ inputs.configuration }}" ${{ inputs.dotnet_build_args }}
          echo "::endgroup::"
        else
          echo "$PROJECTS" | while IFS= read -r proj; do
            proj=$(echo "$proj" | xargs)
            [ -z "$proj" ] && continue

            # Derive subdir from project filename: ComplexityAnalysis.Core.csproj → complexityanalysis-core
            proj_name=$(basename "$proj" .csproj | tr '.' '-' | tr '[:upper:]' '[:lower:]')
            output_dir="${GITHUB_WORKSPACE}/docs/api/${proj_name}"
            mkdir -p "$output_dir"

            echo "::group::dotnet build ${proj} → ${output_dir}/"
            dotnet build "$proj" \
              -c "${{ inputs.configuration }}" \
              -p:MkDocsDocumentationPath="${output_dir}" \
              -p:MkDocsOutputFile="${output_dir}/index.md" \
              -p:MkDocsMergeFiles=false \
              ${{ inputs.dotnet_build_args }}
            echo "::endgroup::"
            echo "::notice::Generated docs: ${proj} → ${output_dir}/"
          done
        fi

    - name: Generate mkdocs.yml if missing
      shell: bash
      run: |
        [ -f mkdocs.yml ] && exit 0

        echo "::notice::No mkdocs.yml found — generating default."
        PROJECTS="${{ inputs.projects }}"

        if [ -z "$PROJECTS" ]; then
          cat > mkdocs.yml <<YAML
        site_name: "${{ inputs.site_name }}"
        docs_dir: docs
        site_dir: site
        theme:
          name: material
        YAML
        else
          {
            echo 'site_name: "${{ inputs.site_name }}"'
            echo "docs_dir: docs"
            echo "site_dir: site"
            echo ""
            echo "theme:"
            echo "  name: material"
            echo "  palette:"
            echo "    - scheme: default"
            echo "      primary: indigo"
            echo ""
            echo "plugins:"
            echo "  - search"
            echo ""
            echo "nav:"
            echo "  - Home: index.md"
            echo "  - API Reference:"

            echo "$PROJECTS" | while IFS= read -r proj; do
              proj=$(echo "$proj" | xargs)
              [ -z "$proj" ] && continue
              proj_name=$(basename "$proj" .csproj | tr '.' '-' | tr '[:upper:]' '[:lower:]')
              # Display name: last segment after final dot
              display=$(basename "$proj" .csproj | sed 's/.*\.//')
              echo "      - ${display}: api/${proj_name}/index.md"
            done
          } > mkdocs.yml
        fi

    - name: Install MkDocs dependencies
      shell: bash
      run: |
        set -euo pipefail
        echo "::group::pip install"
        python -m pip install --upgrade pip
        if [ -f docs/requirements.txt ]; then
          pip install -r docs/requirements.txt
        elif [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "::notice::No requirements.txt found — installing mkdocs-material."
          pip install mkdocs-material==9.5.18
        fi
        echo "::endgroup::"

    - name: Build MkDocs site
      if: ${{ inputs.build_site == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        STRICT_FLAG=""
        if [ "${{ inputs.strict }}" = "true" ]; then
          STRICT_FLAG="--strict"
        fi
        echo "::group::mkdocs build"
        mkdocs build --clean $STRICT_FLAG ${{ inputs.mkdocs_build_args }}
        echo "::endgroup::"
        echo "::notice::Site built at: site/"
